<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FImageStack.Core\FImageStack.Core.csproj" />
    <ProjectReference Include="..\FImageStack.Infrastructure\FImageStack.Infrastructure.csproj" />
    <ProjectReference Include="..\FImageStack.Application\FImageStack.Application.csproj" />
  </ItemGroup>

</Project>
